name: Testing Github Action Workflows

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    unit_testing:
        runs-on: ubuntu-latest
        steps:
            # Checking out the code
            - name: Check out the code
              uses: actions/checkout@v3
            
            - name: Setting up Python Env
              uses: actions/setup-python@v3
              with:
                    python-version: '3.10'
            - name: Installing Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            
            - name: Running Tests
              run: pytest